apiVersion: v1
kind: Secret
metadata:
  name: quay-creds
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: skopeotest
  password: Skopeo@1
