# End to end pipeline.
# Prior to running the pipeline, ensure that you have attached the Workspace, created the required Secret, and deployed the 'git-clone' task within your environment.
# Refer to https://hub.tekton.dev/tekton/task/git-clone for guidance on implementing the 'git-clone' task.

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: redhat-dependency-analytics-pipeline
spec:
  workspaces:
    - name: output
  params:
  - name: github-url
  - name: manifest-file-path
  - name: project-directory-path
  - name: output-file-path
  - name: image
  tasks:
    # git-clone-project task
    - name: git-clone-project
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: $(params.github-url)
        - name: subdirectory
          value: $(params.project-directory-path)
    # redhat-dependency-analytics task
    - name: redhat-dependency-analytics
      taskRef:
        name: redhat-dependency-analytics
      runAfter:
        - git-clone-project
      workspaces:
        - name: output
          workspace: output
      params:
        - name: manifest-file-path
          value: $(params.manifest-file-path)
        - name: project-directory-path
          value: $(params.project-directory-path)
        - name: output-file-path
          value: $(params.output-file-path)
        - name: image
          value: $(params.image)
